<p class="titre"><img src="pictures/logo.png" class="titre" alt="bande du site"></p>
			<nav>
				<ul id="menu">
       				 <li>
                 		 <a href="index.php">accueil</a>
        			 </li>
        
        			 <li>
                		 <a href="#">Produits</a>
                	 		 <ul>
                        		 <li><a href="maisons.php">Maisons</a></li>
                        		 <li><a href="appartements.php">Appartements</a></li>
                             <li><a href="locaux.php">Locaux Commerciaux</a></li>
                             <li><a href="immeuble.php">Immeubles</a></li>
                             <li><a href="terrainus.php">Terrains nus</a></li>
                	 		 </ul>

        			 </li>

        			 <li>
                		 <a href="#">plus</a>
                		 	 <ul>
                        	 	 <li><a href="forum.php">forum</a></li>
                       			 <li><a href="liens.php">liens</a></li>
                    		     <li><a href="contact.php">nous contacter</a></li>
                    		     <li><a href="team.php">team</a></li>
                                     <li><a href="deconnexion.php">Se deconnecter</a></li>
                                     <li><a href='gererLesBiens.php'>Gérer les biens</a></li>
                                     <li><a href='stats.php'>Voir les statistiques</a></li>
                                     <li><a href="ajouterUtilisateur.php">Cliquez ici pour ajouter un administrateur</a></li>
               				 </ul>
       				 </li>
				</ul>
			</nav>
